// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/facilities": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List facilities the current user administers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_httpx.AdminFacility"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_httpx.errorEnvelope"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/internal_httpx.errorEnvelope"
                        }
                    }
                }
            }
        },
        "/airports/{icao}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "Airport metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Airport ICAO (e.g. KATL)",
                        "name": "icao",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/veids_api_internal_vatsim.AirportData"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_httpx.errorEnvelope"
                        }
                    }
                }
            }
        },
        "/airports/{icao}/weather": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "METAR-only airport weather",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Airport ICAO (e.g. KATL)",
                        "name": "icao",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/veids_api_internal_atis.Report"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log out (revoke refresh token, clear cookies)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current authenticated user (with permissions + facilities)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_httpx.errorEnvelope"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Rotate refresh token and mint a new access JWT",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/internal_httpx.errorEnvelope"
                        }
                    }
                }
            }
        },
        "/auth/vatsim/callback": {
            "get": {
                "tags": [
                    "auth"
                ],
                "summary": "VATSIM OAuth callback",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Authorization code",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "CSRF state",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Found"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_httpx.errorEnvelope"
                        }
                    }
                }
            }
        },
        "/auth/vatsim/login": {
            "get": {
                "tags": [
                    "auth"
                ],
                "summary": "Begin VATSIM OAuth login",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/charts": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charts"
                ],
                "summary": "Airport charts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Airport ICAO (e.g. KATL)",
                        "name": "airport",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/veids_api_internal_vatsim.ChartSet"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_httpx.errorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_httpx.errorEnvelope"
                        }
                    }
                }
            }
        },
        "/dashboards/default": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboards"
                ],
                "summary": "Get the user's default dashboard config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_httpx.errorEnvelope"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboards"
                ],
                "summary": "Save the user's default dashboard config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "boolean"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_httpx.errorEnvelope"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_httpx.errorEnvelope"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_httpx.AdminFacility": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "region": {
                    "type": "integer"
                },
                "roles": {
                    "description": "the current user's role keys at this facility",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "staff": {
                    "description": "facility staff CIDs, synced from VATUSA",
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer",
                        "format": "int64"
                    }
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "internal_httpx.errorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "veids_api_internal_atis.Report": {
            "type": "object",
            "properties": {
                "airportName": {
                    "type": "string"
                },
                "altimeter": {
                    "type": "number"
                },
                "atisAvailable": {
                    "type": "boolean"
                },
                "atisLetter": {
                    "type": "string"
                },
                "atisText": {
                    "type": "string"
                },
                "flightCategory": {
                    "$ref": "#/definitions/veids_api_internal_parser.FlightCategory"
                },
                "icao": {
                    "type": "string"
                },
                "metar": {
                    "type": "string"
                },
                "wind": {
                    "$ref": "#/definitions/veids_api_internal_parser.Wind"
                }
            }
        },
        "veids_api_internal_parser.FlightCategory": {
            "type": "string",
            "enum": [
                "VFR",
                "MVFR",
                "IFR",
                "LIFR"
            ],
            "x-enum-varnames": [
                "VFR",
                "MVFR",
                "IFR",
                "LIFR"
            ]
        },
        "veids_api_internal_parser.Wind": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string"
                },
                "gust": {
                    "type": "integer"
                },
                "speed": {
                    "type": "integer"
                }
            }
        },
        "veids_api_internal_vatsim.AirportData": {
            "type": "object",
            "properties": {
                "airportName": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "faaIdent": {
                    "type": "string"
                },
                "fullState": {
                    "type": "string"
                },
                "icaoIdent": {
                    "type": "string"
                },
                "military": {
                    "type": "boolean"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "veids_api_internal_vatsim.Chart": {
            "type": "object",
            "properties": {
                "chartCode": {
                    "type": "string"
                },
                "chartName": {
                    "type": "string"
                },
                "chartSeq": {
                    "type": "integer"
                },
                "pdfName": {
                    "type": "string"
                },
                "pdfPath": {
                    "type": "string"
                }
            }
        },
        "veids_api_internal_vatsim.ChartSet": {
            "type": "object",
            "properties": {
                "airportName": {
                    "type": "string"
                },
                "apd": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/veids_api_internal_vatsim.Chart"
                    }
                },
                "city": {
                    "type": "string"
                },
                "dp": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/veids_api_internal_vatsim.Chart"
                    }
                },
                "faaIdent": {
                    "type": "string"
                },
                "fullState": {
                    "type": "string"
                },
                "iap": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/veids_api_internal_vatsim.Chart"
                    }
                },
                "icaoIdent": {
                    "type": "string"
                },
                "lah": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/veids_api_internal_vatsim.Chart"
                    }
                },
                "military": {
                    "type": "boolean"
                },
                "min": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/veids_api_internal_vatsim.Chart"
                    }
                },
                "star": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/veids_api_internal_vatsim.Chart"
                    }
                },
                "state": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "CookieAuth": {
            "type": "apiKey",
            "name": "veids_at",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "vE-IDS API",
	Description:      "The vE-IDS controller IDS API: VATSIM OAuth authentication, saved dashboards, charts/airport info, a live datafeed/ATIS WebSocket, and facility administration. All non-auth endpoints require the access-JWT cookie.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
