// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO accounts (
    user_id, type, provider, provider_account_id,
    refresh_token, access_token, expires_at, token_type, scopes, id_token, session_state
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (provider, provider_account_id) DO UPDATE SET
    user_id       = EXCLUDED.user_id,
    refresh_token = EXCLUDED.refresh_token,
    access_token  = EXCLUDED.access_token,
    expires_at    = EXCLUDED.expires_at,
    token_type    = EXCLUDED.token_type,
    scopes        = EXCLUDED.scopes,
    id_token      = EXCLUDED.id_token,
    session_state = EXCLUDED.session_state,
    updated_at    = now()
`

type UpsertAccountParams struct {
	UserID            string      `json:"user_id"`
	Type              string      `json:"type"`
	Provider          string      `json:"provider"`
	ProviderAccountID string      `json:"provider_account_id"`
	RefreshToken      pgtype.Text `json:"refresh_token"`
	AccessToken       pgtype.Text `json:"access_token"`
	ExpiresAt         pgtype.Int4 `json:"expires_at"`
	TokenType         pgtype.Text `json:"token_type"`
	Scopes            []string    `json:"scopes"`
	IDToken           pgtype.Text `json:"id_token"`
	SessionState      pgtype.Text `json:"session_state"`
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.Exec(ctx, upsertAccount,
		arg.UserID,
		arg.Type,
		arg.Provider,
		arg.ProviderAccountID,
		arg.RefreshToken,
		arg.AccessToken,
		arg.ExpiresAt,
		arg.TokenType,
		arg.Scopes,
		arg.IDToken,
		arg.SessionState,
	)
	return err
}
