// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: atis_state.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listAtisState = `-- name: ListAtisState :many
SELECT station, code_letter, raw_report, updated_at FROM atis_state
`

func (q *Queries) ListAtisState(ctx context.Context) ([]AtisState, error) {
	rows, err := q.db.Query(ctx, listAtisState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AtisState
	for rows.Next() {
		var i AtisState
		if err := rows.Scan(
			&i.Station,
			&i.CodeLetter,
			&i.RawReport,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAtisState = `-- name: UpsertAtisState :exec
INSERT INTO atis_state (station, code_letter, raw_report, updated_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (station) DO UPDATE SET
    code_letter = EXCLUDED.code_letter,
    raw_report  = EXCLUDED.raw_report,
    updated_at  = now()
`

type UpsertAtisStateParams struct {
	Station    string      `json:"station"`
	CodeLetter pgtype.Text `json:"code_letter"`
	RawReport  []byte      `json:"raw_report"`
}

func (q *Queries) UpsertAtisState(ctx context.Context, arg UpsertAtisStateParams) error {
	_, err := q.db.Exec(ctx, upsertAtisState, arg.Station, arg.CodeLetter, arg.RawReport)
	return err
}
