// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboards.sql

package sqlc

import (
	"context"
)

const deleteDashboard = `-- name: DeleteDashboard :exec
DELETE FROM dashboard_layouts WHERE id = $1 AND user_id = $2
`

type DeleteDashboardParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDashboard(ctx context.Context, arg DeleteDashboardParams) error {
	_, err := q.db.Exec(ctx, deleteDashboard, arg.ID, arg.UserID)
	return err
}

const getDashboard = `-- name: GetDashboard :one
SELECT id, user_id, name, config, is_default, created_at, updated_at FROM dashboard_layouts WHERE id = $1 AND user_id = $2
`

type GetDashboardParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) GetDashboard(ctx context.Context, arg GetDashboardParams) (DashboardLayout, error) {
	row := q.db.QueryRow(ctx, getDashboard, arg.ID, arg.UserID)
	var i DashboardLayout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDefaultDashboard = `-- name: GetDefaultDashboard :one
SELECT id, user_id, name, config, is_default, created_at, updated_at FROM dashboard_layouts
WHERE user_id = $1 AND is_default = true
ORDER BY updated_at DESC
LIMIT 1
`

func (q *Queries) GetDefaultDashboard(ctx context.Context, userID string) (DashboardLayout, error) {
	row := q.db.QueryRow(ctx, getDefaultDashboard, userID)
	var i DashboardLayout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDashboards = `-- name: ListDashboards :many
SELECT id, user_id, name, config, is_default, created_at, updated_at FROM dashboard_layouts WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListDashboards(ctx context.Context, userID string) ([]DashboardLayout, error) {
	rows, err := q.db.Query(ctx, listDashboards, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardLayout
	for rows.Next() {
		var i DashboardLayout
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Config,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDashboard = `-- name: UpsertDashboard :one
INSERT INTO dashboard_layouts (id, user_id, name, config, is_default)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (id) DO UPDATE SET
    name       = EXCLUDED.name,
    config     = EXCLUDED.config,
    is_default = EXCLUDED.is_default,
    updated_at = now()
RETURNING id, user_id, name, config, is_default, created_at, updated_at
`

type UpsertDashboardParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Name      string `json:"name"`
	Config    []byte `json:"config"`
	IsDefault bool   `json:"is_default"`
}

func (q *Queries) UpsertDashboard(ctx context.Context, arg UpsertDashboardParams) (DashboardLayout, error) {
	row := q.db.QueryRow(ctx, upsertDashboard,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Config,
		arg.IsDefault,
	)
	var i DashboardLayout
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Config,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
