// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facilities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGrantsBySource = `-- name: DeleteGrantsBySource :exec
DELETE FROM user_facility_roles WHERE source = $1
`

// The syncer wipes all grants from a given source (e.g. 'vatusa') before
// reinserting the fresh set, leaving grants from other sources (e.g. 'manual')
// untouched. Run inside the same transaction as the reinserts.
func (q *Queries) DeleteGrantsBySource(ctx context.Context, source string) error {
	_, err := q.db.Exec(ctx, deleteGrantsBySource, source)
	return err
}

const getFacility = `-- name: GetFacility :one
SELECT id, name, url, region, type, active, metadata, synced_at, created_at, updated_at FROM facilities WHERE id = $1
`

func (q *Queries) GetFacility(ctx context.Context, id string) (Facility, error) {
	row := q.db.QueryRow(ctx, getFacility, id)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Region,
		&i.Type,
		&i.Active,
		&i.Metadata,
		&i.SyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserFacilityRoles = `-- name: GetUserFacilityRoles :many
SELECT
    ufr.facility_id,
    ufr.role_key,
    ufr.source,
    f.name     AS facility_name,
    f.url      AS facility_url,
    f.region   AS facility_region,
    f.active   AS facility_active,
    f.metadata AS facility_metadata
FROM user_facility_roles ufr
LEFT JOIN facilities f ON f.id = ufr.facility_id
WHERE ufr.cid = $1
ORDER BY ufr.facility_id, ufr.role_key
`

type GetUserFacilityRolesRow struct {
	FacilityID       pgtype.Text `json:"facility_id"`
	RoleKey          string      `json:"role_key"`
	Source           string      `json:"source"`
	FacilityName     pgtype.Text `json:"facility_name"`
	FacilityUrl      pgtype.Text `json:"facility_url"`
	FacilityRegion   pgtype.Int4 `json:"facility_region"`
	FacilityActive   pgtype.Bool `json:"facility_active"`
	FacilityMetadata []byte      `json:"facility_metadata"`
}

// Every (facility, role) a controller holds, with the facility's display fields.
// LEFT JOIN so system-wide grants (facility_id IS NULL) still return.
func (q *Queries) GetUserFacilityRoles(ctx context.Context, cid string) ([]GetUserFacilityRolesRow, error) {
	rows, err := q.db.Query(ctx, getUserFacilityRoles, cid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserFacilityRolesRow
	for rows.Next() {
		var i GetUserFacilityRolesRow
		if err := rows.Scan(
			&i.FacilityID,
			&i.RoleKey,
			&i.Source,
			&i.FacilityName,
			&i.FacilityUrl,
			&i.FacilityRegion,
			&i.FacilityActive,
			&i.FacilityMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissions = `-- name: GetUserPermissions :many
SELECT DISTINCT rp.permission_key
FROM user_facility_roles ufr
JOIN role_permissions rp ON rp.role_key = ufr.role_key
WHERE ufr.cid = $1
ORDER BY rp.permission_key
`

// The distinct set of permission keys a controller holds, unioned across every
// role granted to their CID at any facility.
func (q *Queries) GetUserPermissions(ctx context.Context, cid string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, cid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var permission_key string
		if err := rows.Scan(&permission_key); err != nil {
			return nil, err
		}
		items = append(items, permission_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGrant = `-- name: InsertGrant :exec
INSERT INTO user_facility_roles (cid, facility_id, role_key, source, granted_by)
VALUES ($1, $2, $3, $4, $5)
`

type InsertGrantParams struct {
	Cid        string      `json:"cid"`
	FacilityID pgtype.Text `json:"facility_id"`
	RoleKey    string      `json:"role_key"`
	Source     string      `json:"source"`
	GrantedBy  pgtype.Text `json:"granted_by"`
}

func (q *Queries) InsertGrant(ctx context.Context, arg InsertGrantParams) error {
	_, err := q.db.Exec(ctx, insertGrant,
		arg.Cid,
		arg.FacilityID,
		arg.RoleKey,
		arg.Source,
		arg.GrantedBy,
	)
	return err
}

const listFacilities = `-- name: ListFacilities :many
SELECT id, name, url, region, type, active, metadata, synced_at, created_at, updated_at FROM facilities ORDER BY id
`

func (q *Queries) ListFacilities(ctx context.Context) ([]Facility, error) {
	rows, err := q.db.Query(ctx, listFacilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Facility
	for rows.Next() {
		var i Facility
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.Region,
			&i.Type,
			&i.Active,
			&i.Metadata,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFacility = `-- name: UpsertFacility :exec
INSERT INTO facilities (id, name, url, region, active, metadata, synced_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (id) DO UPDATE SET
    name      = EXCLUDED.name,
    url       = EXCLUDED.url,
    region    = EXCLUDED.region,
    active    = EXCLUDED.active,
    metadata  = EXCLUDED.metadata,
    synced_at = now(),
    updated_at = now()
`

type UpsertFacilityParams struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Url      string `json:"url"`
	Region   int32  `json:"region"`
	Active   bool   `json:"active"`
	Metadata []byte `json:"metadata"`
}

// Called by the VATUSA syncer. Core fields are columns; `metadata` carries the
// staff CIDs (and any future per-facility values) as a JSONB bag.
func (q *Queries) UpsertFacility(ctx context.Context, arg UpsertFacilityParams) error {
	_, err := q.db.Exec(ctx, upsertFacility,
		arg.ID,
		arg.Name,
		arg.Url,
		arg.Region,
		arg.Active,
		arg.Metadata,
	)
	return err
}
