// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	UserID            string             `json:"user_id"`
	Type              string             `json:"type"`
	Provider          string             `json:"provider"`
	ProviderAccountID string             `json:"provider_account_id"`
	RefreshToken      pgtype.Text        `json:"refresh_token"`
	AccessToken       pgtype.Text        `json:"access_token"`
	ExpiresAt         pgtype.Int4        `json:"expires_at"`
	TokenType         pgtype.Text        `json:"token_type"`
	Scopes            []string           `json:"scopes"`
	IDToken           pgtype.Text        `json:"id_token"`
	SessionState      pgtype.Text        `json:"session_state"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type AtisState struct {
	Station    string             `json:"station"`
	CodeLetter pgtype.Text        `json:"code_letter"`
	RawReport  []byte             `json:"raw_report"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type DashboardLayout struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	Config    []byte             `json:"config"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Facility struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Url       string             `json:"url"`
	Region    int32              `json:"region"`
	Type      string             `json:"type"`
	Active    bool               `json:"active"`
	Metadata  []byte             `json:"metadata"`
	SyncedAt  pgtype.Timestamptz `json:"synced_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RefreshToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     string             `json:"user_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	ReplacedBy pgtype.UUID        `json:"replaced_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	Key         string             `json:"key"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type RolePermission struct {
	RoleKey       string `json:"role_key"`
	PermissionKey string `json:"permission_key"`
}

type User struct {
	ID            string             `json:"id"`
	Cid           string             `json:"cid"`
	FirstName     string             `json:"first_name"`
	LastName      string             `json:"last_name"`
	Email         string             `json:"email"`
	EmailVerified pgtype.Timestamptz `json:"email_verified"`
	Rating        int32              `json:"rating"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UserFacilityRole struct {
	ID         int64              `json:"id"`
	Cid        string             `json:"cid"`
	FacilityID pgtype.Text        `json:"facility_id"`
	RoleKey    string             `json:"role_key"`
	Source     string             `json:"source"`
	GrantedBy  pgtype.Text        `json:"granted_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
