// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package sqlc

import (
	"context"
)

const upsertPermission = `-- name: UpsertPermission :exec
INSERT INTO permissions (key, name, description)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE SET
    name        = EXCLUDED.name,
    description = EXCLUDED.description
`

type UpsertPermissionParams struct {
	Key         string `json:"key"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) UpsertPermission(ctx context.Context, arg UpsertPermissionParams) error {
	_, err := q.db.Exec(ctx, upsertPermission, arg.Key, arg.Name, arg.Description)
	return err
}

const upsertRole = `-- name: UpsertRole :exec
INSERT INTO roles (key, name, description)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE SET
    name        = EXCLUDED.name,
    description = EXCLUDED.description
`

type UpsertRoleParams struct {
	Key         string `json:"key"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) UpsertRole(ctx context.Context, arg UpsertRoleParams) error {
	_, err := q.db.Exec(ctx, upsertRole, arg.Key, arg.Name, arg.Description)
	return err
}

const upsertRolePermission = `-- name: UpsertRolePermission :exec
INSERT INTO role_permissions (role_key, permission_key)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type UpsertRolePermissionParams struct {
	RoleKey       string `json:"role_key"`
	PermissionKey string `json:"permission_key"`
}

func (q *Queries) UpsertRolePermission(ctx context.Context, arg UpsertRolePermissionParams) error {
	_, err := q.db.Exec(ctx, upsertRolePermission, arg.RoleKey, arg.PermissionKey)
	return err
}
